language: ruby
sudo: required
dist: trusty
install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - "sudo apt-get install -y bc libc6:i386 libstdc++6:i386 zlib1g:i386 gcc-multilib"
env:
  matrix:
   - DEFCONFIG_NAME=arcturus_ucls1012a_defconfig
script:
- echo 'Clone buildroot repository'
- git clone https://github.com/hmahadik/buildroot
- cd buildroot
- make ${DEFCONFIG_NAME}
- while true ; sleep 60; do echo "Still building" ; done &
- stupidpid=$!
- echo 'Build buildroot'
- |
make > >(tee build.log) 2>&1 || (echo 'Failed build last output' && tail -200 build.log && exit 1)
- kill ${stupidpid}
- echo 'Display end of log'
- tail -1000 build.log
- ls -lash output/images

